### ISSUE TITLE
[eng] Don't fuck it up!

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#1]
https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=Don%27t%20fuck%20it%20up%21

Cannot choose the German translation "Versau es nicht!" as I put ")" as a category:
ERROR: bad API response status.

I was wondering whether . is the umbrella category for all punctuations.
Cause in rebanked CCG comma, period, quotes and brackets have different categories.

**Comment by texttheater** [comment]
Should be fixed by d435894. Note that the category for ) is RRB in CCGrebank.

Good point about the punctuation categories! We should stick with what CCGrebank does.

**Comment by kovvalsky** [comment]
Since you renamed "period" category with ".", I thought RBR could be ")".
So what is the full list of non-standard categories at this moment?
Is the comma category treated as period?

**Comment by texttheater** [comment]
Exactly as in CCGrebank:

* `,` for commas
* `.` for sentence-final punctuation (., ?, !)
* `LRB` for left round brackets
* `RRB` for right round brackets
* `LQU` for left quotes
* `RQU` for right quotes

I don’t know of any `period` category. Is that used anywhere?

**Comment by kovvalsky** [comment]
I see. I worked much with the prolog output format that used "comma" and "period" categories, that's why I thought so. Thanks.
Accidentally put ",." category for  
https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Auf%20Wiedersehen%2C%20Sayoko.
and getting the same error:
ERROR: bad API response status

**Comment by texttheater** [comment]
Should be fixed now. EasyCCG was accepting anything non-alphanumeric as a punctuation category, but not correctly escaping it for Prolog output.
