### ISSUE TITLE
[ita] Io voglio che Tom venga arrestato.

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#16]
[https://texttheater.net/ccgweb/sentence.php?lang=ita&sentence=Io%20voglio%20che%20Tom%20venga%20arrestato.](https://texttheater.net/ccgweb/sentence.php?lang=ita&sentence=Io%20voglio%20che%20Tom%20venga%20arrestato.)

Unnecessary type raising on "Io".

**Comment by texttheater** [comment]
I think this goes away when you fix the category for the period at the end.

**Comment by kovvalsky** [comment]
You are right. I did't notice the punctuation category.
