### ISSUE TITLE
[eng] It was colder yesterday than today.

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#17]
Some kind of indeterminism in this example:
[https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=It%20was%20colder%20yesterday%20than%20today.](https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=It%20was%20colder%20yesterday%20than%20today.)
(1) When I constraint the whole sentence as a constituent "colder yesterday than today" stays as a constituent.
(2) When "it"'s category is set to NP[expl], "was colder yesterday" becomes a constituent.
(3) When I set the category back to NP, the "was colder yesterday" still stays as a constituent, opposed to what was after (1).

**Comment by texttheater** [comment]
This not necessarily unexpected behavior. The input to the parser is different in (1) and (3): in (1), the category of **It** is unconstrained. In (3), it is constrained to be `NP`. This may influence the order in which items end up on the agenda, I think.

**Comment by kovvalsky** [comment]
I see. Thanks. Since for the current task this is not relevant, I will close it.
