### ISSUE TITLE
[deu] Nehmen Sie ein Taxi zum Hotel.

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#18]
[https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Nehmen%20Sie%20ein%20Taxi%20zum%20Hotel.](https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Nehmen%20Sie%20ein%20Taxi%20zum%20Hotel.)

**zum** gets `PP/N`, **taxi** `N`, **un** `NP/N` and there is no parse.
Set **nehmen** to `((S[b]/NP)/PP)/NP` and **Sie** to `NP`. Still no parse.
Set **Hotel** to `N` and **.** to `S[b]\S[b]`. Still no parse.
The reason can be that there is no type-raising rule: `NP --> S\(S/NP)`

**Comment by kovvalsky** [comment]
![image](https://user-images.githubusercontent.com/12584294/36354042-b0fe7982-14ce-11e8-8108-089b16ac0257.png)

**Comment by texttheater** [comment]
_Nehmen_ should be `((S[b]/PP)/NP)/NP` instead of `((S[b]/NP)/PP)/NP`, shouldn't it?

**Comment by kovvalsky** [comment]
Yes, if `Nehmen Sie zum Hotel ein Taxi` is ungrammatical.
I also didn't opted for `((S[b]/PP)/NP)/NP` because this encourages adverbs of category `S|S`. But that is a minor.

**Comment by texttheater** [comment]
_Nehmen Sie zum Hotel ein Taxi_ is grammatical, but the verb has a different category in each case in our annotation scheme (see manual, section _Argument Order_).

**Comment by kovvalsky** [comment]
The scheme focuses on `NP` arguments that's why I thought it doesn't concern `PP` and `NP` arguments.
So, in the manual do you want to say that if there are **verb**  **pp-phrase**  **n-phrase** and **verb**  **n-phrase**  **p-phrase** orders, two different categories (`(S/NP)/PP` and `(S/PP)/NP` respectively) should be assigned to **verb**?

**Comment by texttheater** [comment]
Yes, correct.
