### ISSUE TITLE
[ita] Windows è il sistema operativo più usato nel mondo.

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#19]
[https://texttheater.net/ccgweb/sentence.php?lang=ita&sentence=Windows%20%C3%A8%20il%20sistema%20operativo%20pi%C3%B9%20usato%20nel%20mondo.](https://texttheater.net/ccgweb/sentence.php?lang=ita&sentence=Windows%20%C3%A8%20il%20sistema%20operativo%20pi%C3%B9%20usato%20nel%20mondo.)

Doesn't do desired forward cross composition over *plu usato* and *nel_mondo*

**Comment by kovvalsky** [comment]
![plu usato nel mondo](https://user-images.githubusercontent.com/12584294/36358198-5d93a6fa-150a-11e8-95dc-c312fd38f13a.png)

**Comment by texttheater** [comment]
Ah, at last a case where category and span BOWs are not enough. I guess to solve this we really do need rule BOWs. I'll implement that.

**Comment by texttheater** [comment]
Actually solved this by refining the tie-breaking heuristic for agenda items in EasyCCG as follows: if two items have the same number of delayed arguments, prefer the one with fewer instances of type-raising.
