### ISSUE TITLE
Reset a user derivation to the auto one

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#2]
Currently BOWs are not visible and probably it is not important that they will be.
Thought It will be nice that one can undo all its edits and get the derivation on its tab that is the same as what is on the auto tab.
One can get auto tree on its tab by copying all (in the worst case) the lexical categories and spans from the auto, but that can be very unpleasant task when sentences are long.

**Comment by texttheater** [comment]
Fixed in ec39dfe8322410c9aedaaabf1047d99e9a416499.
