### ISSUE TITLE
[deu] Englisch sprechen ist schwierig.

### ISSUE THREAD

**Issue by jobos** [texttheater/ccgweb#20]
no parse

[https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Englisch%20sprechen%20ist%20schwierig.](https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Englisch%20sprechen%20ist%20schwierig.)

**Comment by texttheater** [comment]
I peeked at your annotation and saw you have a category `(S[dcl]\\(S[b]\\NP))/(S[adj\\NP)` – there's a closing square bracket missing.
