### ISSUE TITLE
[eng] A glass of water, please: S or NP?

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#21]
[https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=A%20glass%20of%20water%2C%20please.](https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=A%20glass%20of%20water%2C%20please.)

What final category these phrases should have?
S[b] or S[b]\NP  OR   NP? 

If this phrase is uttered without any previous discourse, I can understand it as imperative.
But if it is an reply to "What would you like to drink?", then it is more NP.

**Comment by texttheater** [comment]
I think this should be `NP`. It may be an imperative semantically, but not syntactically.

**Comment by kovvalsky** [comment]
Now, why I would support NP is that it seems hard to get S category for:
"Un bicchiere d'acqua, per favore"
because, given that the comma is optional, "per" needs to have (S\NP)/NP, which is an uncommon category for a preposition.
