### ISSUE TITLE
[deu] Sie kommen nicht heute: scope of nicht

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#22]
[https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Sie%20kommen%20nicht%20heute.](https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Sie%20kommen%20nicht%20heute.)

 Is it ok if nicht takes scope over heute?
Otherwise VP/VP for 'nicht' seems weird, right?

**Comment by texttheater** [comment]
I think you're right. CCGrebank also has things like `concentrated not|((S\NP)\(S\NP))/((S\NP)\(S\NP)) in the Northwest but in the South`.
