### ISSUE TITLE
(hätte @ (sollen @ ausklinken)) vs (should @ (have @ logged_out))

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#23]
[https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Ich%20h%C3%A4tte%20mich%20nicht%20ausklinken%20sollen.](https://texttheater.net/ccgweb/sentence.php?lang=deu&sentence=Ich%20h%C3%A4tte%20mich%20nicht%20ausklinken%20sollen.)

How would you get "sollen" with a wide scope?
or are we accepting the derivation that leads the following composition?
(nicht (hätte @ (sollen @ (ausklinken @ mich)))) @ Ich

**Comment by texttheater** [comment]
(nicht (hätte @ (sollen @ (ausklinken @ mich)))) @ Ich

I think this is correct, given that we are targeting syntax and not semantics. Syntactically, it is pretty clear that _hätte_ takes scope over _sollen_, because _hätte_ is the inflected verb.

Nice example of a translation divergence!

**Comment by kovvalsky** [comment]
ok, I agree.
