### ISSUE TITLE
[eng] Does she speak English?

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#24]
[https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=Does%20she%20speak%20English%3F](https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=Does%20she%20speak%20English%3F)

Why not
```Does_S[q]/S[b] (she speak English)_S[b]```
instead of
```(Does_(S[q]/(S[b]\NP))/NP she) (speak English)_S[b]\NP```

**Comment by texttheater** [comment]
It is the way of CCGbank and, I think, of many syntactic theories of English to assume that the subject is the subject of the auxiliary in constructions with _do_-support. Why? I'm not sure... one argument could perhaps be that in _Does she by any chance speak English?_ an adverbial modifying the matrix clause can intervene between the subject and the embedded VP. Another, that uninflected VPs are attested in other contexts as well, and uninflected clauses with nominative subjects aren't?
