### ISSUE TITLE
[eng] I will take care of the flowers: 2 or 3 arguments?

### ISSUE THREAD

**Issue by kovvalsky** [texttheater/ccgweb#27]
Judge says 2 arguments
[https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=I%20will%20take%20care%20of%20the%20flowers.](https://texttheater.net/ccgweb/sentence.php?lang=eng&sentence=I%20will%20take%20care%20of%20the%20flowers.)

In the manual it is analyzed with 3 arguments:
https://texttheater.net/ccgweb/manual.php?section=arguments-and-modifiers

**Comment by texttheater** [comment]
Are you sure? This is the analysis of `judge` that I see:

![image](https://user-images.githubusercontent.com/19344/39673347-adda1fec-513a-11e8-9518-9c99ab5fa99e.png)

**Comment by kovvalsky** [comment]
Yes, I see the same. 
I think I misread the strikeout formatting: `take` shouldn't have `((S[b]\NP)/PP)/NP`.
The strikeout actually highlights annotations where disagreements were.   
So, the manual and the judge are consistent in this case.
