### ISSUE TITLE
[rus] Это довольно скучно.

### ISSUE THREAD

**Issue by fleurdhelice** [texttheater/ccgweb#28]
[https://texttheater.net/ccgweb/sentence.php?lang=rus&sentence=%D0%AD%D1%82%D0%BE%20%D0%B4%D0%BE%D0%B2%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%20%D1%81%D0%BA%D1%83%D1%87%D0%BD%D0%BE.](https://texttheater.net/ccgweb/sentence.php?lang=rus&sentence=%D0%AD%D1%82%D0%BE%20%D0%B4%D0%BE%D0%B2%D0%BE%D0%BB%D1%8C%D0%BD%D0%BE%20%D1%81%D0%BA%D1%83%D1%87%D0%BD%D0%BE.)

A new rule might be needed for handling predicative adverbs and adjectives with omitted copula, which is very frequent in Russian.

**Comment by texttheater** [comment]
Thanks for the report! I've added S[adj]\NP → S[dcl]\NP to the type changing rules for Russian.
